FROM node:10-jessie

WORKDIR /src
ADD . .

ARG CI_JOB_AUTH

RUN apt-get update && \
    apt-get -y install git graphicsmagick imagemagick

RUN npm install && \
    apt-get -y remove git && \
    npm install

EXPOSE 5000

CMD ["node", "app.js"]