FROM hypriot/rpi-node

COPY ./ /app

WORKDIR /app

#RUN apt-get update && apt-get install -y iputils-ping net-tools

RUN apt-get update && apt-get install -y graphicsmagick imagemagick

RUN npm install

EXPOSE 5000

ENTRYPOINT ["npm", "start"]

